src/webrms/HotelGlob.RMS.Web/Controllers/GroupCalculationController.cs
using HotelGlob.RMS.Data;
using HotelGlob.RMS.Data.Models;
using Hotels.Basic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Hotels.Config.ConfigModel;
using Newtonsoft.Json;
using HotelGlob.RMS.Adapter;
using System.Data.Entity.Core.Objects;
using System.Data.Entity;
using HotelGlob.RMS.BL;

namespace HotelGlob.RMS.Web.Controllers
{
    public class GroupCalculationController : Controller
    {
        private RmsDbContext _db = new RmsDbContext();
        private GroupCalculationBL _BLManager = new GroupCalculationBL();
        // GET: GroupCalculation
        public async Task<ActionResult> Index(int id)
        {
            HotelSettings hotel = await _db.HotelSettings.FindAsync(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            var configurationRoot = JsonConvert.DeserializeObject<ConfigurationRoot>(hotel.Settings);
           
            var rmsAdapter = await _BLManager.InitRmsAdapter(DateTime.Today, DateTime.Today, id,_db);
            var roomTypes = _db.RoomTypes.Where(c => c.HotelId == id).ToList();
            var mealTypes = _db.MealTypes.ToList();
            Session["rmsAdapter"] = rmsAdapter;
            var input = _BLManager.GetCalcInputForIndex(rmsAdapter, configurationRoot.RoomTypes.RoomTypeDescriptions.ToDictionary(c=>c.Number, c=>roomTypes.FirstOrDefault(s=>s.Id==c.Number)?.Name), configurationRoot.MealTypes.MealTypeDescriptions.ToDictionary(c=>c.Number, c=>mealTypes.FirstOrDefault(s => s.Id == c.Number)?.Name));
            input.HotelId = id;
            return View(input);
        }
        
        [HttpPost]
        public async Task<ActionResult> GetOutputPartialView(GroupCalcInput viewModel)
        {
            IEnumerable<GroupCalculationResult>  result = await
                Task.Run(() =>
            {
                var rmsAdapter = (RmsAdapter)Session["rmsAdapter"];
                if (rmsAdapter!= null)
                    return  rmsAdapter.RunGroupCalculationPriceCalculation(viewModel);
                return null;
            });
            return PartialView("GroupCalcOutputList", result);
        }
        [HttpPost]
        public async Task<ActionResult> GetInputPartialView(GroupCalcInput viewModel)
        {
            var rmsAdapter = await _BLManager.InitRmsAdapter(viewModel.Start, viewModel.End, viewModel.HotelId, _db);
            Session["rmsAdapter"] = rmsAdapter;
            ModelState.Clear();
            return PartialView("GroupCalcInputList", _BLManager.GetInputPartialView(viewModel, rmsAdapter));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/webrms/HotelGlob.RMS.Web/Views/GroupCalculation/GroupCalcInputList.cshtml
@model Hotels.Basic.GroupCalcInput

<div class="form-horizontal">
    <table style="width:100%">
        <tr>
            <th>Date</th>
            @{
                if (Model.Inputs.Count > 0)
                {
                    foreach (var room in Model.Inputs[0].RoomTypes)
                    {
                        <th>Room Type @room.Value.Name</th>
                    }
                    if (Model.Inputs[0].MealTypes != null && Model.Inputs[0].MealTypes.Any())
                    {
                        foreach (var meal in Model.Inputs[0].MealTypes)
                        {
                            <th>Meal Type @meal.Value.Name</th>
                        }
                    }
                }
            }
        <tr />
        @{
            for (int i = 0; i < Model.Inputs.Count; i++)
            {
                <tr>
                    <td>@Model.Inputs[i].Date.ToShortDateString()</td>
                    @Html.HiddenFor(model => model.Inputs[i].Date)
                    @{foreach (var room in Model.Inputs[0].RoomTypes)
                        {
                            <td>
                                <div>@Html.EditorFor(model => model.Inputs[i].RoomTypes[room.Key].Value)</div>
                                <div> @Model.Inputs[i].RoomTypes[room.Key].EmptyRooms / @Model.Inputs[i].RoomTypes[room.Key].PlanEmptyRooms</div>
                            </td>
                            @Html.HiddenFor(model => model.Inputs[i].RoomTypes[room.Key].PlanEmptyRooms)
                            @Html.HiddenFor(model => model.Inputs[i].RoomTypes[room.Key].EmptyRooms)
                        }
                        if (Model.Inputs[0].MealTypes != null && Model.Inputs[0].MealTypes.Any())
                        {
                            foreach (var meal in Model.Inputs[0].MealTypes)
                            {
                                <td style="vertical-align: top" >
                                    <div >@Html.EditorFor(model => model.Inputs[i].MealTypes[meal.Key])</div>
                                </td>
                            }
                        }
                    }
                </tr>
            }
        }
</table>

</div>

src/webrms/HotelGlob.RMS.Web/Views/GroupCalculation/GroupCalcOutputList.cshtml
@model List<Hotels.Basic.GroupCalculationResult>

<div class="form-horizontal">
    <table style="width:100%">
        <tr>
            <th>Date</th>
            @{
                if (Model.Count() > 0)
                {
                    foreach (var room in Model[0].Results)
                    {
                        <th>Room Type @room.RoomType</th>
                    }
                }
            }
        <tr />
        @{
            for (int i = 0; i < Model.Count(); i++)
            {
                <tr>
                    @Html.HiddenFor(model => model[i].Date)
                    <td>@Model[i].Date.ToShortDateString()</td>
                    @{for (int j = 0; j < Model[0].Results.Count(); j++)
                        {
                            <td style="width:18.5%">
                                @if (Model[i].Results[j].MinPrice > 0)
                                    {
                                    <div>@Html.EditorFor(model => model[i].Results[j].Price)</div>
                                    if (Model[i].Results[j].MaxPrice > 0)
                                    {
                                        <div> @Math.Round(Model[i].Results[j].MinPrice, 2) - @Math.Round(Model[i].Results[j].MaxPrice, 2)}</div>
                                    }
                                    else
                                    {
                                        <div>
                                            @Math.Round(Model[i].Results[j].MinPrice, 2)  -                                       
                                        </div>
                                    }
                                }
                            </td>
                        }
                    }
                </tr>
            }
        }
</table>

</div>

src/webrms/HotelGlob.RMS.Web/Views/GroupCalculation/Index.cshtml
@model Hotels.Basic.GroupCalcInput
@{
    ViewBag.Title = "Group Calculation";
}

<h2>Group Calculation</h2>


<form action="/" id="inputForm">
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model=>model.HotelId)
    <div class="form-horizontal">

        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label  " })
            @Html.EditorFor(model => model.Start, new { @class = "form-control", id = "startDate" })
            @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.End, htmlAttributes: new { @class = "control-label " })
            @Html.EditorFor(model => model.End, new { @class = "form-control", id = "endDate" })
            @Html.ValidationMessageFor(model => model.End, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-12" id="inputView">
            @Html.Partial("GroupCalcInputList", Model)
        </div>

        <div class="form-group col-md-12">
            <input type="button" value="Calculate" class="btn btn-default" id="calcButton" />
        </div>
        <div class="form-group col-md-12" id="outputView" />
    </div>
</form>   

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        <script>
            $(document).ready(function () {
                $("#Start,#End").change(function () {
                    var dtStart=$("#Start").val();
                    var dtEnd = $("#End").val();
                    var json = {
                        Start: dtStart,
                        End: dtEnd,
                        Inputs: @Html.Raw(Model.GetInputsJSON())
                        };
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GetInputPartialView", "GroupCalculation")',
                        data: $("#inputForm").serialize(),
                        success: function (data) {
                            $("#inputView").html(data);
                        }
                    });
                });
                $("#calcButton").click(function () {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("GetOutputPartialView", "GroupCalculation")',
                        data: $("#inputForm").serialize() ,
                        success: function (data) {
                            $("#outputView").html(data);
                        }
                    });
                });
            });
        </script>
    }