src/webrms/HotelGlob.RMS.Web/Controllers/CalculationsController.cs
using HotelGlob.RMS.Data;
using HotelGlob.RMS.Data.Models;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Linq;
using System.Data.Entity;
using System;
using Hotels.Config;
using System.Collections.Generic;
using System.Text;

namespace HotelGlob.RMS.Web.Controllers
{
    public class CalculationsController : Controller
    {
        private RmsDbContext _db = new RmsDbContext();

        // GET: Calculations
        public async Task<ActionResult> Index(int id)
        {
            HotelSettings hotel = await _db.HotelSettings.FindAsync(id);

            if (hotel == null)
            {
                return HttpNotFound("The hotel not found.");
            }

            var calculations = await GetCalculations(0, id);
            DefoConfiguration conf = new DefoConfiguration(hotel.Settings);
            var total = conf.ConfigurationRoot.Categories.BookingPeriods.Any() ? conf.ConfigurationRoot.Categories.BookingPeriods.Count() : 1;
            Dictionary<int, string> stayNames = new Dictionary<int, string>();
            Dictionary<int, string> bookingNames = new Dictionary<int, string>();
            for (int i = 0; i < conf.ConfigurationRoot.Categories.Total; i++)
            {
                int l = (i / total);
                int b = i - l * total;
                var bp = conf.ConfigurationRoot.Categories.BookingPeriods?.FirstOrDefault(c => c.Number == b);
                var sp = conf.ConfigurationRoot.Categories.StayPeriods?.FirstOrDefault(c => c.Number == l);
                bookingNames.Add(i, bp?.LowerBound + "-" + bp?.UpperBound);
                stayNames.Add(i, sp?.LowerBound + "-" + sp?.UpperBound);
            }
            ViewBag.Id = id;
            ViewBag.Num = 0;
            ViewBag.StayNames = stayNames;
            ViewBag.BookingNames = bookingNames;
            return View(calculations);
        }

        private async Task<List<Calculation>> GetCalculations(int num, int id)
        {
            var from = DateTime.Now.Date.AddDays(7 * num);
            var to = DateTime.Now.Date.AddDays(7 * (num + 1));
            
            var queryResult = await _db.Calculations
                .Include(c => c.Predictions)
                .Where(c => c.HotelId == id && c.PredictionDate>= from && c.PredictionDate < to).ToListAsync();
            return await Task.Run(() =>
                    {
                           return queryResult.GroupBy(c => c.PredictionDate.Date).Select(c => c.OrderBy(s => s.CalculatedOn).LastOrDefault()).ToList();
                    });
        }
        
        public ActionResult GetCsv(int hotelId)
        {
            HotelSettings hotel = _db.HotelSettings.Find(hotelId);
            DefoConfiguration conf = new DefoConfiguration(hotel.Settings);
            var total = conf.ConfigurationRoot.Categories.BookingPeriods.Any() ? conf.ConfigurationRoot.Categories.BookingPeriods.Count() : 1;
            Dictionary<int, string> stayNames = new Dictionary<int, string>();
            Dictionary<int, string> bookingNames = new Dictionary<int, string>();
            for (int i = 0; i < conf.ConfigurationRoot.Categories.Total; i++)
            {
                int l = (i / total);
                int b = i - l * total;
                var bp = conf.ConfigurationRoot.Categories.BookingPeriods?.FirstOrDefault(c => c.Number == b);
                var sp = conf.ConfigurationRoot.Categories.StayPeriods?.FirstOrDefault(c => c.Number == l);
                bookingNames.Add(i, bp?.LowerBound + " - " + bp?.UpperBound);
                stayNames.Add(i, sp?.LowerBound + " - " + sp?.UpperBound);
            }
            var queryResult = _db.Calculations
               .Include(c => c.Predictions)
               .Where(c => c.HotelId == hotelId).ToList();
            
            var calcs=queryResult.GroupBy(c => c.PredictionDate.Date).Select(c => c.OrderBy(s => s.CalculatedOn).LastOrDefault()).ToList();
            var sb = new StringBuilder();
            sb.AppendLine(string.Join(";", new string[] { "Date","Room Type", "Meal Type", "Stay period", "Booking period", "People Number", "Price", "Expected Load", "Cancelation", "No Shows" }));
            foreach (var calc in calcs)
            {
                foreach(var pred in calc.Predictions)
                    sb.AppendLine(string.Join(";",new string[]{ calc.PredictionDate.ToShortDateString(),pred.RoomType.Name,pred.MealType.Name, stayNames[pred.CategoryType],bookingNames[pred.CategoryType],pred.PeopleNum.ToString(), pred.Price.ToString(), pred.ExpectedLoad.ToString(),pred.Cancelation.ToString(), pred.NoShows.ToString() }));
            }
            return File(Encoding.Default.GetBytes(sb.ToString()), System.Net.Mime.MediaTypeNames.Application.Octet, "ResultsCsv.csv");            
        }
        [HttpGet]
        public async Task<ActionResult> PredictionsOutputList(int num,int id)
        {
            HotelSettings hotel = await _db.HotelSettings.FindAsync(id);

            if (hotel == null)
            {
                return HttpNotFound("The hotel not found.");
            }
            var calculations = await GetCalculations(num, id);
            DefoConfiguration conf = new DefoConfiguration(hotel.Settings);
            var total = conf.ConfigurationRoot.Categories.BookingPeriods.Any() ? conf.ConfigurationRoot.Categories.BookingPeriods.Count() : 1;
            Dictionary<int, string> stayNames = new Dictionary<int, string>();
            Dictionary<int, string> bookingNames = new Dictionary<int, string>();
            for (int i = 0; i < conf.ConfigurationRoot.Categories.Total; i++)
            {
                int l = (i / total);
                int b = i - l * total;
                var bp = conf.ConfigurationRoot.Categories.BookingPeriods?.FirstOrDefault(c => c.Number == b);
                var sp = conf.ConfigurationRoot.Categories.StayPeriods?.FirstOrDefault(c => c.Number == l);
                bookingNames.Add(i, bp?.LowerBound + (bp?.UpperBound > 365 ? "+" : ("-" + bp?.UpperBound)));
                stayNames.Add(i, sp?.LowerBound + (sp?.UpperBound>365?"+":("-" + sp?.UpperBound)));
            }
            ViewBag.StayNames = stayNames;
            ViewBag.BookingNames = bookingNames;
            ViewBag.Num = num;
            ViewBag.Id = id;
            return PartialView("PredictionsOutputList", calculations);
        }

        public async Task<ActionResult> Details(int id)
        {
            var calculation = await this._db.Calculations.Include(c => c.Predictions).FirstOrDefaultAsync(c => c.Id == id);
            return View(calculation);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/webrms/HotelGlob.RMS.Web/Controllers/ConfigurationController.cs
using HotelGlob.RMS.Data;
using HotelGlob.RMS.Data.Models;
using HotelGlob.RMS.Web.Models.Configuration;
using Hotels.Config;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace HotelGlob.RMS.Web.Controllers
{
    public class ConfigurationController : Controller
    {
        private RmsDbContext db = new RmsDbContext();
        // GET: Configuration
        public async Task<ActionResult> Index(int hotelId)
        {
            ViewBag.HotelId = hotelId;
            HotelSettings hotel =await db.HotelSettings.FindAsync(hotelId);
            var roomTypes = db.RoomTypes.Where(c=>c.HotelId==hotelId).ToList();
            var mealTypes = db.MealTypes.ToList();
            DefoConfiguration conf = new DefoConfiguration(hotel.Settings);
            var model = ConfigurationViewModel.Map(conf.ConfigurationRoot, roomTypes);
            model.RoomTypes.IsEditable = !hotel.IsSettingsBlocked;
            ViewBag.DbMealTypes = new SelectList(mealTypes, "Id", "Name");
            ViewBag.DbRoomTypes = new SelectList(roomTypes, "RoomTypeCode", "Name");
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(int hotelId, ConfigurationViewModel config)
        {
            var roomTypes = db.RoomTypes.Where(c => c.HotelId == hotelId).ToList();
            if (ModelState.IsValid)
            {
                if (config.RoomTypes.IsEditable)
                {
                    var newRoomTypes = config.RoomTypes.RoomTypes.Where(c => c.Number == 0).ToList();
                    if (newRoomTypes.Any())
                        db.RoomTypes.AddRange(newRoomTypes.Select(c => new RoomType { Name = c.Name, RoomTypeCode = c.RoomTypeCode, HotelId = hotelId }));
                    db.RoomTypes.RemoveRange(roomTypes.Where(c =>! config.RoomTypes.RoomTypes.Any(s => s.Number == c.Id)));
                    foreach (var item in config.RoomTypes.RoomTypes.Where(c => c.Number > 0).ToList())
                    {
                        var entity = roomTypes.FirstOrDefault(c => c.Id == item.Number);
                        if (entity != null)
                        {
                            entity.RoomTypeCode = item.RoomTypeCode;
                            entity.Name = item.Name;
                            db.Entry(entity).State = EntityState.Modified;
                        }
                    }
                    await db.SaveChangesAsync();
                    roomTypes = db.RoomTypes.Where(c => c.HotelId == hotelId).ToList();
                }
                
                HotelSettings hotel = await db.HotelSettings.FindAsync(hotelId);
                if (config.MealTypes.UseInDynamicCalculation)
                    config.RoomTypes.RoomTypeCoefs.Clear();
                hotel.Settings = JsonConvert.SerializeObject(ConfigurationViewModel.Map(config, roomTypes), Formatting.Indented);
                db.Entry(hotel).State = EntityState.Modified;
                await db.SaveChangesAsync();
                
                return RedirectToAction("Index","HotelSettings");
            }
            ViewBag.HotelId = hotelId;             
            var mealTypes = db.MealTypes.ToList();
            ViewBag.DbMealTypes = new SelectList(mealTypes, "Id", "Name");
            ViewBag.DbRoomTypes = new SelectList(roomTypes, "RoomTypeCode", "Name");
            return View(config);
        }
    }
}

src/webrms/HotelGlob.RMS.Web/Controllers/HotelSettingsController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using HotelGlob.RMS.Data;
using HotelGlob.RMS.Data.Models;

namespace HotelGlob.RMS.Web.Controllers
{
    public class HotelSettingsController : Controller
    {
        private RmsDbContext db = new RmsDbContext();

        // GET: Hotels
        public async Task<ActionResult> Index()
        {
            return View(await db.HotelSettings.ToListAsync());
        }

        // GET: Hotels/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HotelSettings hotel = await db.HotelSettings.FindAsync(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // GET: Hotels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Hotels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Name,Settings,IsRmsEnalbed")] HotelSettings hotel)
        {
            if (ModelState.IsValid)
            {
                db.HotelSettings.Add(hotel);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(hotel);
        }

        // GET: Hotels/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HotelSettings hotel = await db.HotelSettings.FindAsync(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // POST: Hotels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Settings,IsRmsEnalbed,IsNeedRecalc")] HotelSettings hotel)
        {
            if (ModelState.IsValid)
            {
                HotelSettings hotelUp = await db.HotelSettings.FindAsync(hotel.Id);
                hotelUp.Name = hotel.Name;
                hotelUp.IsNeedRecalc = hotel.IsNeedRecalc;
                hotelUp.IsRmsEnalbed = hotel.IsRmsEnalbed;
                hotelUp.Settings = hotel.Settings;
                db.Entry(hotelUp).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(hotel);
        }

        // GET: Hotels/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HotelSettings hotel = await db.HotelSettings.FindAsync(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // POST: Hotels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            HotelSettings hotel = await db.HotelSettings.FindAsync(id);
            db.HotelSettings.Remove(hotel);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/webrms/HotelGlob.RMS.Web/Views/HotelSettings/Create.cshtml
@model HotelGlob.RMS.Data.Models.HotelSettings

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Hotel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Settings, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Settings, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Settings, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsRmsEnalbed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsRmsEnalbed)
                    @Html.ValidationMessageFor(model => model.IsRmsEnalbed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/webrms/HotelGlob.RMS.Web/Views/HotelSettings/Delete.cshtml
@model HotelGlob.RMS.Data.Models.HotelSettings

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hotel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Settings)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Settings)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

src/webrms/HotelGlob.RMS.Web/Views/HotelSettings/Details.cshtml
@using HotelGlob.RMS.Data.Models
@model HotelGlob.RMS.Data.Models.HotelSettings

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Hotel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Settings)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Settings)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.IsRmsEnalbed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsRmsEnalbed)
        </dd>
    </dl>
</div>

<table class="table">
    <thead>
        <tr>
            <th>CreatedOn</th>
            <th>Body</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var log in Model.Logs.OrderByDescending(l => l.CreatedOn))
        {
            <tr class="@(log.LogType == LogType.Error ? "danger" : "")">
                <td>@log.CreatedOn</td>
                <td>@log.Body</td>
            </tr>
        }
    </tbody>
</table>

<p>
    <a href="@Url.Action("Index", "Calculations", new { id = Model.Id })">View calculations</a> |
    @Html.ActionLink("Edit", "Edit", new {id = Model.Id}) |
    @Html.ActionLink("Back to List", "Index")
</p>

src/webrms/HotelGlob.RMS.Web/Views/HotelSettings/Edit.cshtml
@model HotelGlob.RMS.Data.Models.HotelSettings

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Hotel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Settings, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Settings, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Settings, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.IsRmsEnalbed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsRmsEnalbed)
                    @Html.ValidationMessageFor(model => model.IsRmsEnalbed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IsNeedRecalc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsNeedRecalc)
                    @Html.ValidationMessageFor(model => model.IsNeedRecalc, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/webrms/HotelGlob.RMS.Web/Views/HotelSettings/Index.cshtml
@model IEnumerable<HotelGlob.RMS.Data.Models.HotelSettings>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Settings)
        </th>*@
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Settings)
        </td>*@
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Calculations", "Index", "Calculations", new { Id = item.Id }, null) |
            @Html.ActionLink("Calculations CSV", "GetCsv", "Calculations", new { hotelId = item.Id }, null) |
            @Html.ActionLink("Events", "Index","Events", new { hotelId = item.Id },null) |
            @Html.ActionLink("Settings", "Index", "Configuration", new { hotelId = item.Id }, null) |
            @Html.ActionLink("Parser Settings", "Index", "Parser_RoomInfo", new { hotelId = item.Id }, null) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>